// @vitest-environment node
import { describe, expect, it } from "vitest";
import { argon2Master } from "./argon2";
import { AttachmentDecryptor, decryptAttachment, encryptAttachment } from "./attachments";
import {
  decryptLabelName,
  decryptMetadata,
  decryptNote,
  decryptTagName,
  encryptLabelName,
  encryptMetadata,
  encryptNote,
  encryptTagName,
  extractTags,
  normalizeTag,
  tagToken,
} from "./content";
import { dataKeyContext, importDataKey, recoveryContext, unwrapDataKey, wrapDataKey } from "./datakey";
import { fromBase64, toBase64, toHex, uuidv7 } from "./encoding";
import { DecryptionError } from "./envelope";
import { hkdfBytes, importAesKey } from "./kdf";
import { deriveRecoveryKeys, formatRecoveryKey, parseRecoveryKey } from "./recovery";
import v from "./test-vectors.json";

// These vectors are generated by the independent C# implementation (E2eeVectorTests). Matching them byte for byte
// proves both follow docs/e2ee-spec.md identically.

const b = fromBase64;
const pattern = (length: number) => Uint8Array.from({ length }, (_, i) => i % 251);

describe("E2EE test vectors", () => {
  it("derive the password keys", async () => {
    const master = await argon2Master(v.kdf.password, {
      salt: b(v.kdf.saltB64),
      memoryKiB: v.kdf.memoryKiB,
      iterations: v.kdf.iterations,
      parallelism: v.kdf.parallelism,
    });

    expect(toBase64(master)).toBe(v.kdf.masterB64);
    expect(toBase64(await hkdfBytes(master, "maple-notes/v2/auth"))).toBe(v.kdf.authKeyB64);
    expect(toBase64(await hkdfBytes(master, "maple-notes/v2/wrap"))).toBe(v.kdf.wrapKeyB64);
  });

  it("derive the data-key subkeys", async () => {
    const dataKey = b(v.dataKeyB64);

    expect(toBase64(await hkdfBytes(dataKey, "maple-notes/v2/e2ee/note"))).toBe(v.subkeys.noteKeyB64);
    expect(toBase64(await hkdfBytes(dataKey, "maple-notes/v2/e2ee/metadata"))).toBe(v.subkeys.metadataKeyB64);
    expect(toBase64(await hkdfBytes(dataKey, "maple-notes/v2/e2ee/tag-index"))).toBe(v.subkeys.tagIndexKeyB64);
  });

  it("wrap and unwrap the data key", async () => {
    const wrapKey = await importAesKey(b(v.kdf.wrapKeyB64));

    const wrapped = await wrapDataKey(wrapKey, b(v.dataKeyB64), dataKeyContext(v.ids.userId), b(v.wrappedDataKey.nonceB64));

    expect(toBase64(wrapped)).toBe(v.wrappedDataKey.envelopeB64);
    const keys = await unwrapDataKey(wrapKey, wrapped, dataKeyContext(v.ids.userId));
    expect(await decryptNote(keys, v.ids.userId, v.ids.noteId, b(v.note.envelopeB64))).toBe(v.note.plaintext);
  });

  it("encrypt note text", async () => {
    const keys = await importDataKey(b(v.dataKeyB64));

    const envelope = await encryptNote(keys, v.ids.userId, v.ids.noteId, v.note.plaintext, b(v.note.nonceB64));

    expect(toBase64(envelope)).toBe(v.note.envelopeB64);
    await expect(decryptNote(keys, v.ids.userId, uuidv7(), envelope)).rejects.toBeInstanceOf(DecryptionError);
  });

  it("compute tag tokens and encrypt tag names", async () => {
    const keys = await importDataKey(b(v.dataKeyB64));

    expect(normalizeTag(v.tag.name)).toBe(v.tag.normalized);
    expect(await tagToken(keys, v.tag.name)).toBe(v.tag.token);
    const envelope = await encryptTagName(keys, v.ids.userId, v.tag.token, v.tag.name, b(v.tag.nonceB64));
    expect(toBase64(envelope)).toBe(v.tag.encryptedNameB64);
    expect(await decryptTagName(keys, v.ids.userId, v.tag.token, envelope)).toBe(v.tag.normalized);
  });

  it("format, parse and use the recovery key", async () => {
    const recoveryKey = b(v.recovery.keyB64);

    expect(formatRecoveryKey(recoveryKey)).toBe(v.recovery.displayed);
    expect(toBase64(parseRecoveryKey(v.recovery.displayed))).toBe(v.recovery.keyB64);
    expect(toBase64(parseRecoveryKey(` ${v.recovery.displayed.toLowerCase().replace(/-/g, " ")} `))).toBe(v.recovery.keyB64);
    expect(toBase64(await hkdfBytes(recoveryKey, "maple-notes/v2/recovery/wrap"))).toBe(v.recovery.wrapKeyB64);

    const derived = await deriveRecoveryKeys(recoveryKey);
    expect(toBase64(derived.authKey)).toBe(v.recovery.authKeyB64);
    const wrapped = await wrapDataKey(derived.wrapKey, b(v.dataKeyB64), recoveryContext(v.ids.userId), b(v.recovery.nonceB64));
    expect(toBase64(wrapped)).toBe(v.recovery.wrappedDataKeyB64);
  });

  it("reject malformed recovery keys", () => {
    expect(() => parseRecoveryKey("too-short")).toThrow();
    expect(() => parseRecoveryKey(v.recovery.displayed.replace(/.$/, "U"))).toThrow(); // U is not in the alphabet
  });

  it("encrypt attachments and decrypt any chunk", async () => {
    const keys = await importDataKey(b(v.dataKeyB64));
    const plaintext = pattern(v.attachment.plaintextLength);

    const encrypted = await encryptAttachment(keys, v.ids.userId, v.ids.attachmentId, new Blob([plaintext]), {
      salt: b(v.attachment.saltB64),
    });
    const bytes = new Uint8Array(await encrypted.arrayBuffer());

    expect(bytes.length).toBe(v.attachment.encryptedLength);
    expect(toHex(new Uint8Array(await crypto.subtle.digest("SHA-256", bytes)))).toBe(v.attachment.encryptedSha256Hex);

    const decrypted = new Uint8Array(await (await decryptAttachment(keys, v.ids.userId, v.ids.attachmentId, encrypted)).arrayBuffer());
    expect(decrypted).toEqual(plaintext);

    const reader = await AttachmentDecryptor.create(keys, v.ids.userId, v.ids.attachmentId, bytes.subarray(0, 42), bytes.length);
    const range = reader.cipherRange(1, 1);
    expect(await reader.decryptChunks(1, bytes.subarray(range.start, range.end))).toEqual(plaintext.subarray(65536));

    const truncated = new Blob([bytes.subarray(0, bytes.length - 1)]);
    await expect(decryptAttachment(keys, v.ids.userId, v.ids.attachmentId, truncated)).rejects.toBeInstanceOf(DecryptionError);
  });

  it("encrypt attachment metadata", async () => {
    const keys = await importDataKey(b(v.dataKeyB64));

    const envelope = await encryptMetadata(keys, v.ids.userId, v.ids.attachmentId, v.metadata.json, b(v.metadata.nonceB64));

    expect(toBase64(envelope)).toBe(v.metadata.envelopeB64);
    expect(await decryptMetadata(keys, v.ids.userId, v.ids.attachmentId, envelope)).toEqual({
      name: "sunset.png",
      type: "image/png",
      size: 70000,
    });
  });

  it("encrypt label names for their label", async () => {
    const keys = await importDataKey(b(v.dataKeyB64));

    const envelope = await encryptLabelName(keys, v.ids.userId, v.ids.labelId, v.label.name, b(v.label.nonceB64));

    expect(toBase64(envelope)).toBe(v.label.encryptedNameB64);
    expect(await decryptLabelName(keys, v.ids.userId, v.ids.labelId, envelope)).toBe(v.label.name);
    await expect(decryptLabelName(keys, v.ids.userId, uuidv7(), envelope)).rejects.toBeInstanceOf(DecryptionError);
  });
});

describe("tag extraction", () => {
  it("matches the server's rules", () => {
    expect(extractTags("Buy milk #Groceries #work/meetings- and #1 or `#code` word#not https://x.com/#anchor #café")).toEqual([
      "groceries",
      "work/meetings",
      "café",
    ]);
    expect(extractTags("# Heading\n```\n#fenced\n```\n#after")).toEqual(["after"]);
  });
});

describe("uuidv7", () => {
  it("produces version 7 UUIDs that sort by time", () => {
    const first = uuidv7(1_700_000_000_000);
    const second = uuidv7(1_700_000_000_001);

    expect(first).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
    expect(first < second).toBe(true);
  });
});
